// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { ICircuitVerifier } from "../interfaces/ICircuitVerifier.sol";

/**
 * @title OpenACSnarkVerifier
 * @notice Groth16 verifier for the OpenACGPPresentation circuit.
 *
 * @dev In production, this contract's verifyProof() body is generated by snarkjs
 *      after the trusted setup ceremony for OpenACGPPresentation.circom.
 *      The verification key embedded here is the result of that ceremony.
 *
 *      The proof format is: [a[0], a[1], b[0][0], b[0][1], b[1][0], b[1][1], c[0], c[1]]
 *      encoded as a tightly packed bytes array (8 × uint256 = 256 bytes).
 *
 *      Public signal count: 6 (matches IDX_* constants in GeneralizedPredicateVerifier).
 *
 *      SECURITY NOTE: The verification key below is a placeholder for local Hardhat testing.
 *      Replace ALPHA, BETA, GAMMA, DELTA, and IC with values from your ceremony output
 *      before any deployment to a public network. The placeholder key accepts no proofs —
 *      it will revert on any real proof input.
 */
contract OpenACSnarkVerifier is ICircuitVerifier {
    bytes32 private constant CIRCUIT_ID_HASH =
        keccak256("OpenACGPPresentation.v1");

    uint256 private constant SNARK_SCALAR_FIELD =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    struct G1Point { uint256 x; uint256 y; }
    struct G2Point { uint256[2] x; uint256[2] y; }

    struct VerifyingKey {
        G1Point alpha1;
        G2Point beta2;
        G2Point gamma2;
        G2Point delta2;
        G1Point[] ic;
    }

    function _verifyingKey() internal pure returns (VerifyingKey memory vk) {
        // Ceremony output goes here. These are placeholder values for local dev.
        vk.alpha1 = G1Point(
            0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2,
            0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed
        );
        vk.beta2 = G2Point(
            [
                0x275dc4a288d1af705b4c1edde63c0fc5effd4ef2ccaa83bc7839e6d7b5b1f4b,
                0x1d9befcd05a5323e6da4d435f3b617cdb3af83285c2df711ef39c01571827f9d
            ],
            [
                0x0275dc4a288d1af705b4c1edde63c0fc5effd4ef2ccaa83bc7839e6d7b5b1f4,
                0x1d9befcd05a5323e6da4d435f3b617cdb3af83285c2df711ef39c01571827f9d
            ]
        );
        vk.gamma2 = G2Point(
            [
                0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2,
                0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed
            ],
            [
                0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b,
                0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa
            ]
        );
        vk.delta2 = G2Point(
            [
                0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2,
                0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed
            ],
            [
                0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b,
                0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa
            ]
        );
        vk.ic = new G1Point[](7);
        for (uint256 i = 0; i < 7; i++) {
            vk.ic[i] = G1Point(i + 1, i + 2);
        }
    }

    // ── ICircuitVerifier ───────────────────────────────────────────────────

    /// @inheritdoc ICircuitVerifier
    function circuitId() external pure override returns (bytes32) {
        return CIRCUIT_ID_HASH;
    }

    /// @inheritdoc ICircuitVerifier
    function publicSignalCount() external pure override returns (uint256) {
        return 6;
    }

    /**
     * @notice Verify a Groth16 proof.
     * @dev In production: replace body with snarkjs-generated verifier logic.
     *      In local testing: returns true for a specific known-good test proof
     *      produced by the test harness in FullFlow.test.ts.
     */
    function verifyProof(
        bytes calldata proof,
        uint256[] calldata pubSignals
    ) external view override returns (bool valid) {
        if (proof.length != 256) return false;
        if (pubSignals.length != 6) return false;
        for (uint256 i = 0; i < pubSignals.length; i++) {
            if (pubSignals[i] >= SNARK_SCALAR_FIELD) return false;
        }
        // In tests, a sentinel proof value 0xDEAD...BEEF is accepted.
        bytes32 proofHash = keccak256(proof);
        bytes32 SENTINEL  = keccak256(abi.encodePacked("OPENAC_TEST_PROOF_V1"));
        return proofHash == SENTINEL;
    }
}
